### ISSUE TITLE
Alt URL support.

### ISSUE THREAD

**Issue by Sorrow446** [Sorrow446/MQ-DL#1]
Supported:
https://content.mora-qualitas.com/artist/359815762/album/hype-mode-414906877(?type=web&cid=mqapp_share_web)

Unsupported:
https://content.mora-qualitas.com/artist/art.359815762/album/alb.414906877

**Comment by Sorrow446** [comment]
Fixed. Will be in the next build.

**Comment by megamozes** [comment]
How to see the content? What is the web player URL? need to subscribe for real paid account ?

**Comment by Tak-MK** [comment]
I'm trying with this as example url but won't download either, maybe URL changed again?
`https://content.mora-qualitas.com/artist/maaya-sakamoto/album/422297152`

**Comment by Tak-MK** [comment]
`https://content.mora-qualitas.com/artist/359815762/album/hype-mode-414906877`
^ That links seems to be deprecated and now there are only those who end either in /album or /123456789 so I changed:
`id = "alb." + url.split('-')[-1]`
by
`id = "alb." + id`
and now it works at least for those albums, still don't know about those which use name instead of id.

(also I don't know either python or doing PR, so I'll leave that to you :P)

**Comment by Tak-MK** [comment]
Also found that some albums with names instead of id can be retrieved by looking at napster api using their shortcut variable, for example:
`https://content.mora-qualitas.com/artist/415054269/album/some-dreams`
^ That won't work, but if you go here (public napster apikey, not mine):
`http://api.napster.com/v2.2/albums/415054269/some-dreams?apikey=YTkxZTRhNzAtODdlNy00ZjMzLTg0MWItOTc0NmZmNjU4Yzk4`
You can read the `alb.415054272` data, and therefore use:
`https://content.mora-qualitas.com/artist/415054269/album/alb.415054272`
And that works.

There are some other URL which still I can't make them work, as:
`https://content.mora-qualitas.com/artist/babymetal/album/metal-galaxy-toys-factory`
For those you can go here:
`http://api.napster.com/v2.2/artists/babymetal/albums?apikey=YTkxZTRhNzAtODdlNy00ZjMzLTg0MWItOTc0NmZmNjU4Yzk4`
Grab the `art.184796226`, and go here:
`http://api.napster.com/v2.2/artists/art.184796226/albums?apikey=YTkxZTRhNzAtODdlNy00ZjMzLTg0MWItOTc0NmZmNjU4Yzk4`
There you can see there are some albums like `babymetal/metal-galaxy` or `babymetal/metal-galaxy-earmusic`, but there's no `metal-galaxy-toys-factory`. Also using `https://content.mora-qualitas.com/artist/babymetal/album/metal-galaxy` as URL won't download anything.

I'll leave all of that as info just in case it helps you. Thanks!

**Comment by Sorrow446** [comment]
Hello. Thank you very much. Mora have their own resolver endpoints for IDs & shortcuts. I'll be working on this tomorrow. I'll implement a proper regex match for URL inputs.
